query GetContactPage {
    contactPage {
        title
        bgColor
        showDiscount
        header
        promocode
        promocodeColor
        promocodeFooter
        promocodeFooterColor
        footer
        media {
            alternativeText
            caption
            ext
            mime
            name
            provider
            url
        }
        mobileMedia {
            alternativeText
            caption
            ext
            mime
            name
            provider
            url
        }
        seo {
            metaTitle
            metaDescription
            canonicalURL
            keywords
            metaRobots
            metaImage {
                url
            }
            openGraph {
                ogTitle
                ogDescription
                ogUrl
                ogType
                ogImage {
                    url
                }
            }
        }
    }
}
