query GetConfig {
    config {
        address
        documentId
        email
        phone
        yandexMapKey
        cookieBanner {
            header
            content
        }
        catalogSettings {
            enableAutoload
            pageSize
            id
        }
    }
}
